# Basic
title: KaiXiu
subtitle: 这是我第一个的博客
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 这是一个新的世界.
creator: <a href="http://bukaixiu.vip">@BuKaiXiu</a>

url: "http://bukaixiu.vip"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: My Projects, url: ''}
    # http://project.onevcat.com
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [bukaixiu-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: bu-kaixiu
    # duoshuo: 
    
# Social
social:
    weibo: bukaixiu
    github: bukaixiu
    twitter: bukaixiu
    gplus: 107108267983477358170
    mail: bukaiixu@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
